# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_item_items_item_id_delete(self) -> None:
        """Test case for delete_item_items_item_id_delete

        Delete Item  # noqa: E501
        """
        pass

    def test_get_item_items_get(self) -> None:
        """Test case for get_item_items_get

        Get Item  # noqa: E501
        """
        pass

    def test_get_items_items_item_id_get(self) -> None:
        """Test case for get_items_items_item_id_get

        Get Items  # noqa: E501
        """
        pass

    def test_get_top_get(self) -> None:
        """Test case for get_top_get

        Get Top  # noqa: E501
        """
        pass

    def test_login_for_access_token_token_post(self) -> None:
        """Test case for login_for_access_token_token_post

        Login For Access Token  # noqa: E501
        """
        pass

    def test_post_item_items_post(self) -> None:
        """Test case for post_item_items_post

        Post Item  # noqa: E501
        """
        pass

    def test_post_items_items_item_id_post(self) -> None:
        """Test case for post_items_items_item_id_post

        Post Items  # noqa: E501
        """
        pass

    def test_put_item_items_item_id_put(self) -> None:
        """Test case for put_item_items_item_id_put

        Put Item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
